URL_GITHUB_LOGIN: "https://github.com"
URL_GITHUB: "https://api.github.com"
CLIENT_ID: dce7e3025651dbf7d995
CLIENT_SECRET: 97d201be7a1b0c9022f39c157b15087dc4dfc9e9


server:
  port: 8080

oauth:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  redirect: "http://localhost:3000/redirect"

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 06d84754c830891922dc
            clientSecret: 99cafe8a565c6e4d4f26c893b4ed9979cbf7df55
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: tag-your-star
      username: admin
      password: admin

  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO
