URL_GITHUB_LOGIN: "https://github.com"
URL_GITHUB: "https://api.github.com"
CLIENT_ID: dce7e3025651dbf7d995
CLIENT_SECRET: 97d201be7a1b0c9022f39c157b15087dc4dfc9e9

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev

security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user
    client:
      client-id: 06d84754c830891922dc
      client-secret: 99cafe8a565c6e4d4f26c893b4ed9979cbf7df55
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      #      redirect-uri: http://localhost/redirect
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO
